Update marketo api
canonical-web-and-design/charmed-osm.com pull request #131
Opened 2022-01-28 14:14 UTC by minkyngkm

## Done
- Post forms to https://ubuntu.com/marketo/submit
- Decapitalise input names
- Update hidden inputs
- Remove recaptcha

## QA

1. Go to  
2. Fill in the form and submit it
3. Check the form is submitted and redirects to a thank you page on charmed-osm.com
4. Check the submitted data is on the list in marketo

## Issue / Card

Fixes #129

2022-01-28 14:14 UTC, webteam-app commented
Demo starting at https://charmed-osm-com-131.demos.haus

2022-01-28 14:42 UTC, anthonydillon requested changes
Some suggestions in the code

2022-01-28 14:42 UTC, anthonydillon commented on templates/index.html
> +            <input value="1212" p-buttonname="formid" type="hidden">
Extra p-button here

2022-01-28 14:42 UTC, anthonydillon commented on templates/index.html
> -            <input type="hidden" name="ret" value="http://charmed-osm.com/thank-you">
Send this form doesn't have a return URL

2022-01-28 14:57 UTC, minkyngkm commented
Thanks @anthonydillon for reviewing.

QA done for the `/contact-us` page
![image](https://user-images.githubusercontent.com/57550290/151568503-2b8809b0-2c3b-4826-8b42-12f556f8b5c1.png)

One question is [the interactive form](https://charmed-osm-com-131.demos.haus/#get-in-touch)'s form id is same as this static [contact-us form](https://charmed-osm-com-131.demos.haus/contact-us) even though the required input fields are different. I failed QAing the interactive form. 😔

2022-02-02 09:54 UTC, anthonydillon commented
The form id is ok to be the same but the interactive form textarea update is not working: 
![image](https://user-images.githubusercontent.com/1413534/152131508-c346cf4c-e8e0-477b-8183-9dc64eec1b2b.png)

2022-02-04 09:47 UTC, anthonydillon approved these changes
LGTM :+1: with a small content update

2022-02-04 09:47 UTC, anthonydillon commented on templates/contact-us/index.html
> +              <label for="phone">phone number:</label>
```suggestion
              <label for="phone">Phone number:</label>
```

2022-02-04 10:00 UTC, merged